
project_id = "mzfdftspnfzusrxoexvl"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3000"

[auth.email]
enabled = true

[realtime]
enabled = true

[analytics]
enabled = false
port = 54327

[vector]
enabled = false

[functions.fetch-cve-data]
verify_jwt = false

[functions.enrich-cve-data]
verify_jwt = false

[functions.generate-japanese-blog]
verify_jwt = false

[functions.scheduled-tasks]
verify_jwt = false
