// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mzfdftspnfzusrxoexvl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16ZmRmdHNwbmZ6dXNyeG9leHZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3MDM3OTksImV4cCI6MjA2MzI3OTc5OX0.FLT-Pfz0aqHXkbFfo_W5mXwi0hJiJKD3HOBnqRD8vjw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);